# yaml-language-server: $schema=https://gitlab.com/api/v4/projects/konradodwrot%2Fgo-modules/packages/generic/che-schema/v0.0.1-che-min-v0.0.96/che.schema.json
##[>] 🤖🤖
profilesDefinitions:
  sandbox-image:
    type: host
    include:
      profiles:
        - url: https://gitlab.com/konradodwrot/tools-configs
          ref: "${{ var.TOOLS_CONFIGS_REF }}"
          specDirPath: .
          profileNames:
            - base/packages
            - specDirPath: profiles/dev
              profileName: dev/virt/linux
            - specDirPath: profiles/shell
              profileName: shell/virt/linux
        - url: https://gitlab.com/konradodwrot/ai-harness/ai-tools-configs
          ref: "${{ var.AI_TOOLS_CONFIGS_REF }}"
          specDirPath: .
          profileName: ai/virt/linux
        - url: https://gitlab.com/konradodwrot/tools-configs
          ref: "${{ var.TOOLS_CONFIGS_REF }}"
          specDirPath: .
          profileNames:
            - specDirPath: profiles/cloud
              profileName: cloud/virt/linux
            - specDirPath: profiles/misc
              profileName: misc/virt/linux
            - specDirPath: profiles/git
              profileName: git/virt/linux
            - specDirPath: profiles/gitlab
              profileName: gitlab/virt/linux

variablesDefinitions:
  all: {scope: recursiveSpecsAndProfiles, required: true}
  specVariablesDefinitions:
    CENTRALIZED_ASSETS_PROSE_AI_REF: null
    PROSE_SPEC_REF: null
##[<] 🤖🤖
