# yaml-language-server: $schema=https://gitlab.com/konradodwrot/go-modules/-/raw/main/che/assets/data/che.schema.json
##[>] 🤖🤖
sandbox-image:
  include:
    profiles:
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/dev/che.yml::dev/virt/linux"
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/shell/che.yml::shell/virt/linux"
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/llm/che.yml::llm/virt/linux"
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/cloud/che.yml::cloud/virt/linux"
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/misc/che.yml::misc/virt/linux"
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/git/che.yml::git/virt/linux"
      - source: "@https://gitlab.com/konradodwrot/configs//profiles/gitlab/che.yml::gitlab/virt/linux"
##[<] 🤖🤖
